apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-coin
spec:
  selector:
    matchLabels:
      app: simple-coin
  template:
    metadata:
      labels:
        app: simple-coin
    spec:
      containers:
      - name: simple-coin
        image: hillpro/simple-coin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
          hostPort: 3001
        - containerPort: 6001
          hostPort: 6001
